emorihouse/emorihouse.github.io

- _includes/member.html
> edit kanahebi profile

- _includes/member.html
> update yadaita profile

- _includes/member.html
> プロフィール追加しました。

- _includes/about.html
- _includes/contact.html
コンタクトフォームの説明書きを変えてみました。
どうでしょうか〜？
> Change contact form description

- _includes/member.html
> add ta8co profile

- _includes/members.html
> メンバーリストにプロフィール追加

- _includes/members.html
自分のメンバープロフィールを追加させていただきました！
また、kiryuanzuさんの文章が一部消えちゃってたみたいなので、ついでに直しておきました。
ご確認をお願いいたします！:bow:
> Add meru's profile

- _includes/members.html
プロフィールを追記しました。
実は人生で初めてのpull request です！！！！！
> add nyanco profile

- _includes/members.html
プロフィール情報追加しました。
これでよいのでしょうか。
修正点あればおしらせください。
> add members

- _includes/members.html
- div要素からはみ出た記述を見つけたため、修正させていただきました！
- 自分のプロフィールを追加しました。
> momokawausa

- _layouts/home2020.html
申し込みフォームで、未入力でも「SEND」できてしまってたので、
とりいそぎすべてrequiredにしました。
他のバリデーションは様子をみて追加していこう...
> modify to required field

- _layouts/home2020.html
今年もよろしくお願いします！表示は崩れてないので大丈夫だと思います！スクショの撮り方が悪くて境界線がわからないのはごめんなさい…。
---
> add sakahukamaki

- _layouts/home2020.html
めるさんとUndoさんをMembersに追加しました。
あわせて、ようさんの画像が表示されなくなっていたので、画像パスも修正しました。
> add Meru-san and Undo-san to members

- _layouts/home2020.html
> add shikibum

- _layouts/home2020.html
- assets/css/style2020.scss
- assets/js/main2020.js
スパム？セールス？の問い合わせが邪魔なので、reCAPTCHA v2 をいれてみました。
これでなくなるといいなあ。
> introduce reCAPTCHA v2

- _includes/2023/members.html
> add beta_chelsea

- _includes/2023/members.html
> add asya81

- _includes/2023/members.html
> add pupupopo88

- _includes/2023/members.html
> add aoirolamp

- README.md
- _includes/2023/members.html
- _includes/2024/members.html
やったこと
- 2024参加表明
- 2023のアイコンリンク切れ対応
- READMEに動作確認のためのサーバー起動方法を明記
> Add sakahukamaki & なんかいろいろ

- _includes/2024/members.html
自己紹介追加させていただきました！
確認をよろしくお願いします！🙏
**確認のスクリーンショット**
> Add motohiro

- _includes/2024/members.html
遅くなりすみません💦
私のプロフィールを追加したので、お手隙の際にご確認ください🙇
よろしくお願いいたします。
> Add Judeee

- _includes/2024/members.html
自己紹介追加いたしました！
改めまして、よろしくお願いします！
> Add yokomaru

- _includes/2024/members.html
> add_bore-ko

- _includes/2024/members.html
> Add ishikawa999

- _includes/2025/members.html
> Add Michelle to 2025 Members

- _includes/2025/members.html
よろしくお願いします〜〜
おそらくコンフリクトしますが、PR出した時点ではこんな感じに表示されてました
> Add pupupopo88 to 2025 members

- _includes/2025/members.html
> add mksaijo

- _includes/2025/members.html
> Add aoirolamp to 2025 members

- _includes/2025/members.html
> Add Kasa to 2025 members
